

import React, { createContext, useState, useEffect, ReactNode, useCallback } from 'react';
import type { Locale } from '../types';

// Expanded translation dictionary
const translations = {
  'ar-EG': {
    dashboard: 'الرئيسية',
    pos: 'الكاشير',
    sales: 'المبيعات',
    purchases: 'المشتريات',
    inventory: 'المخزن',
    customers: 'الزباين',
    hr: 'شؤون الموظفين',
    attendance: 'الحضور والانصراف',
    menu: 'المنيو',
    recipes: 'الوصفات والتكاليف',
    kitchen: 'المطبخ الرئيسي',
    delivery: 'مناطق التوصيل',
    branches: 'الفروع',
    daily_ops: 'تشغيل اليوم',
    pnl: 'الأرباح والخساير',
    reports: 'التقارير',
    settings: 'الإعدادات',
    system_name: 'نظام النواجي الذكي',
    theme: 'شكل البرنامج',
    language: 'اللغة',
    total_sales: 'إجمالي المبيعات',
    new_customers: 'زباين جداد',
    avg_order_value: 'متوسط قيمة الأوردر',
    top_selling_item: 'أكتر حاجة بتتباع',
    generating_kpis: 'بنجهّزلك أرقام الأداء...',
    generate_menu_ideas: 'اقترحلي أصناف جديدة',
    generating_ideas: 'بنجيبلك أفكار...',
    order_total: 'الإجمالي',
    pay_now: 'حاسب',
    categories: 'الأقسام',
    items: 'الأصناف',
    your_order: 'أوردرك',
    search_items: 'دور على صنف...',
    greeting: 'أهلاً بيك تاني،',
    subtitle: 'ده ملخص سريع لحركة الشغل النهاردة.',
    select_customer: 'اختار زبون',
    walk_in_customer: 'زبون طيّاري',
    add_discount: 'ضيف خصم',
    cash: 'كاش',
    card: 'كارت',
    online: 'أونلاين',
    employee_management: 'إدارة الموظفين',
    employee_subtitle: 'اعرض، ابحث، وعدّل بيانات كل الموظفين.',
    add_employee: 'ضيف موظف جديد',
    search_employees: 'دور على موظف...',
    generating_employees: 'بنحمّل بيانات الموظفين...',
    name: 'الاسم',
    position: 'الوظيفة',
    branch: 'الفرع',
    salary: 'المرتب',
    status: 'الحالة',
    actions: 'إجراءات',
    view_details: 'عرض التفاصيل',
    view_short: 'عرض',
    edit_short: 'تعديل',
    sales_management: 'إدارة المبيعات',
    sales_subtitle: 'تابع كل الفواتير وعروض الأسعار من كل الفروع.',
    add_sale: 'فاتورة جديدة',
    search_sales: 'دور في المبيعات...',
    generating_sales: 'بنحمّل بيانات المبيعات...',
    customer: 'الزبون',
    total: 'الإجمالي',
    date: 'التاريخ',
    inventory_management: 'إدارة المخزن',
    inventory_subtitle: 'راقب كميات المخزون، التحويلات، وتنبيهات نواقص البضاعة.',
    add_item: 'ضيف صنف للمخزن',
    search_inventory: 'دور في المخزن...',
    generating_inventory: 'بنحمّل بيانات المخزن...',
    item_name: 'اسم الصنف',
    category: 'القسم',
    stock_level: 'الكمية الحالية',
    reorder_level: 'حد إعادة الطلب',
    supplier: 'المورّد',
    customer_management: 'إدارة الزباين',
    customer_subtitle: 'ابني علاقات مع زباينك واعملهم برامج ولاء.',
    add_customer: 'ضيف زبون جديد',
    search_customers: 'دور على زبون...',
    generating_customers: 'بنحمّل بيانات الزباين...',
    email: 'الإيميل',
    phone: 'رقم الموبايل',
    loyalty_points: 'نقط الولاء',
    last_order: 'آخر أوردر',
    purchases_management: 'إدارة المشتريات',
    purchases_subtitle: 'تابع أوردرات الشرا، الفواتير، وعلاقاتك مع الموردين.',
    add_purchase: 'ضيف فاتورة شرا',
    search_purchases: 'دور في المشتريات...',
    generating_purchases: 'بنحمّل بيانات المشتريات...',
    order_id: 'رقم الأوردر',
    amount: 'المبلغ',
    attendance_management: 'الحضور الذكي',
    attendance_subtitle: 'حلل وراقب التزام موظفينك، مع تحليلات ذكية.',
    search_attendance: 'دور في الحضور...',
    generating_attendance: 'بنحمّل سجلات الحضور...',
    employee_name: 'اسم الموظف',
    check_in: 'وقت الحضور',
    check_out: 'وقت الانصراف',
    duration: 'مدة الشغل',
    recipes_management: 'الوصفات والتكاليف',
    recipes_subtitle: 'اعمل وصفاتك، واحسب تكلفتها وهامش ربحها بالظبط.',
    add_recipe: 'ضيف وصفة',
    search_recipes: 'دور على وصفة...',
    generating_recipes: 'بنحمّل الوصفات...',
    recipe_name: 'اسم الوصفة',
    food_cost_perc: 'نسبة تكلفة الأكل',
    gross_margin: 'هامش الربح',
    ingredients: 'المكونات',
    kitchen_management: 'إدارة المطبخ الرئيسي',
    kitchen_subtitle: 'نسّق طلبات التحضير والتوزيع على الفروع.',
    search_kitchen_orders: 'دور في طلبات المطبخ...',
    generating_kitchen_orders: 'بنحمّل طلبات المطبخ...',
    destination_branch: 'الفرع المستلم',
    prep_status: 'حالة التحضير',
    prep_time: 'وقت التحضير',
    delivery_management: 'إدارة مناطق التوصيل',
    delivery_subtitle: 'حدد مناطق التوصيل، مصاريفها، وتابع السواقين.',
    add_zone: 'ضيف منطقة',
    zone_name: 'اسم المنطقة',
    delivery_fee: 'مصاريف التوصيل',
    active_drivers: 'السواقين المتاحين',
    avg_delivery_time: 'متوسط وقت التوصيل',
    branches_management: 'إدارة الفروع',
    branches_subtitle: 'نظرة عامة على أداء فروعك وإدارتها.',
    add_branch: 'ضيف فرع',
    branch_name: 'اسم الفرع',
    manager: 'المدير',
    employees: 'الموظفين',
    daily_sales: 'مبيعات النهاردة',
    daily_ops_management: 'إدارة تشغيل اليوم',
    daily_ops_subtitle: 'قوايم مراجعة ومهام عشان تضمن الشغل يمشي زي الساعة.',
    opening_checklist: 'تشيك ليست الصباحية',
    closing_checklist: 'تشيك ليست التقفيل',
    pnl_statement: 'قايمة الأرباح والخساير',
    pnl_subtitle: 'تحليل الأداء المالي للفترة دي.',
    revenue: 'الإيرادات',
    cogs: 'تكلفة البضاعة المباعة',
    gross_profit: 'مجمل الربح',
    operating_expenses: 'المصاريف التشغيلية',
    net_profit: 'صافي الربح',
    reports_center: 'مركز التقارير',
    reports_subtitle: 'اعمل وصدّر تقارير مخصصة لكل حتة في النظام.',
    report_name: 'اسم التقرير',
    description: 'شرح التقرير',
    last_generated: 'آخر مرة اتعمل',
    run_report: 'اعمل التقرير',
    settings_subtitle: 'ظبّط إعدادات البرنامج زي ما تحب.',
    general_settings: 'إعدادات عامة',
    pos_settings: 'إعدادات الكاشير',
    financial_settings: 'إعدادات مالية',
    users_roles: 'المستخدمين والصلاحيات',
    inventory_settings: 'إعدادات المخزن',
    customer_loyalty: 'الزباين والولاء',
    integrations: 'الربط الخارجي',
    security_data: 'الأمان والبيانات',
    company_profile: 'بيانات الشركة',
    company_name: 'اسم الشركة',
    company_logo: 'لوجو الشركة',
    change_logo: 'غيّر اللوجو',
    company_address: 'عنوان الشركة',
    contact_email: 'إيميل التواصل',
    localization: 'اللغة والمنطقة',
    default_language: 'اللغة الأساسية',
    default_currency: 'العملة الأساسية',
    timezone: 'المنطقة الزمنية',
    date_format: 'شكل التاريخ',
    branch_settings: 'إعدادات الفروع',
    allow_inter_branch_transfers: 'السماح بالتحويلات بين الفروع',
    default_branch_new_employees: 'الفرع الأساسي للموظفين الجداد',
    system_behavior: 'سلوك النظام',
    auto_logout_minutes: 'الخروج التلقائي (بالدقايق)',
    enable_end_of_day_report_email: 'تفعيل إيميل تقرير آخر اليوم',
    end_of_day_report_recipients: 'مين يستلم إيميل آخر اليوم',
    payment_methods: 'طرق الدفع',
    enable: 'تفعيل',
    receipt_customization: 'تخصيص الريسيت',
    header_text: 'كلام أول الريسيت',
    footer_text: 'كلام آخر الريسيت',
    order_management: 'إدارة الأوردرات',
    enable_table_management: 'تفعيل إدارة الترابيزات',
    default_order_type: 'نوع الأوردر الأساسي',
    dine_in: 'صالة',
    takeaway: 'تيك أواي',
    delivery_option: 'دليفري',
    enable_order_hold: 'تفعيل تعليق الأوردرات',
    print_kitchen_receipt_auto: 'طباعة ريسيت المطبخ تلقائيًا',
    gratuity_tipping: 'الإكراميات وال팁س',
    enable_tipping_on_card_machine: 'تفعيل الـ "Tip" على ماكينة الدفع',
    suggested_tip_percentages: 'نسب الـ "Tip" المقترحة',
    tax_settings: 'إعدادات الضرايب',
    vat_percentage: 'نسبة ضريبة القيمة المضافة',
    service_charge: 'رسوم الخدمة',
    tax_reg_number: 'رقم التسجيل الضريبي',
    accounting: 'الحسابات',
    fiscal_year_start: 'بداية السنة المالية',
    accounting_integration: 'الربط مع برامج الحسابات',
    auto_sync_daily_sales: 'مزامنة المبيعات اليومية تلقائيًا',
    expense_tracking: 'متابعة المصاريف',
    add_expense_category: 'ضيف فئة مصاريف',
    user_management: 'إدارة المستخدمين',
    invite_user: 'ابعت دعوة لمستخدم',
    role_based_access: 'التحكم في الصلاحيات',
    add_role: 'ضيف صلاحية جديدة',
    manager_role: 'مدير',
    cashier_role: 'كاشير',
    waiter_role: 'ويتر',
    advanced_permissions: 'صلاحيات متقدمة',
    can_give_discounts_above: 'يقدر يدي خصم أكتر من',
    pnl_dashboard: 'لوحة التحكم المالية',
    financial_kpis: 'مؤشرات الأداء الرئيسية',
    gross_profit_margin: 'هامش مجمل الربح',
    net_profit_margin: 'هامش صافي الربح',
    ai_financial_summary: 'ملخص مالي بالذكاء الاصطناعي',
    generating_insights: 'بنحلل البيانات...',
    date_range: 'الفترة الزمنية',
    this_month: 'الشهر ده',
    last_month: 'الشهر اللي فات',
    this_quarter: 'الربع ده من السنة',
    this_year: 'السنة دي',
    all_branches: 'كل الفروع',
    view_mode: 'طريقة العرض',
    standard: 'العادي',
    comparison_pop: 'مقارنة بالفترة اللي فاتت',
    percentage_of_revenue: 'كنسبة من الإيراد',
    budget_vs_actual: 'الميزانية قصاد الفعلي',
    account: 'الحساب',
    current_period: 'الفترة الحالية',
    previous_period: 'الفترة السابقة',
    variance: 'الفرق',
    budget: 'الميزانية',
    actual: 'الفعلي',
    what_if_analysis: 'تحليل "ماذا لو؟"',
    what_if_analysis_desc: 'جرب تأثير أي تغييرات افتراضية على صافي ربحك.',
    what_if_prompt: 'اكتب سيناريو، مثلاً: "يحصل إيه لو الإيجار زاد 10%؟"',
    simulate: 'جرب',
    base_case: 'الوضع الحالي',
    simulated_case: 'الوضع الافتراضي',
    tools: 'أدوات مالية',
    manage_chart_of_accounts: 'إدارة شجرة الحسابات',
    manage_budgets: 'إدارة الميزانيات',
    manual_journal_entry: 'إدخال قيد يدوي',
    close_period: 'قفل الفترة المالية',
    export_pdf: 'تصدير PDF',
    export_excel: 'تصدير Excel',
    feature_in_development: 'معلش، الخاصية دي لسه بتتجهز',
    pos_source: 'من الكاشير',
    inventory_source: 'من المخزن',
    hr_source: 'من الموظفين',
    manual_source: 'إدخال يدوي',
    search_for_customers: 'دور على زبون بالاسم أو الموبايل...',
    customer_profile: 'صفحة الزبون',
    select: 'اختار',
    subtotal: 'المجموع الفرعي',
    tax: 'ضريبة (14%)',
    table_management: 'إدارة الترابيزات',
    active_orders: 'الأوردرات المفتوحة',
    payment: 'الدفع',
    payment_details: 'تفاصيل الدفع',
    amount_received: 'المبلغ المستلم',
    change_due: 'الباقي',
    confirm_payment: 'تأكيد الدفع',
    order_paid_success: 'الأوردر اتحاسب عليه بنجاح!',
    new_order_for_table: 'تم فتح أوردر جديد لترابيزة',
    no_active_order: 'مفيش أوردر مفتوح. لو سمحت اختار ترابيزة الأول.',
    available: 'فاضية',
    occupied: 'مشغولة',
    order_notes_placeholder: 'ملاحظات على الأوردر...',
    offline_mode_active: 'وضع الأوفلاين شغال. الأوردرات هتتظبط أول ما النت يرجع.',
    grid_view: 'عرض مربعات',
    floor_plan: 'رسمة المكان',
    split_bill: 'تقسيم الحساب',
    merge_tables: 'دمج ترابيزات',
    gift_card: 'كارت هدايا',
    split_payment: 'تقسيم الدفع',
    print_receipt: 'اطبع الريسيت',
    email_receipt: 'ابعت الريسيت في إيميل',
    split_by_item: 'تقسيم بالأصناف',
    split_equally: 'تقسيم بالتساوي',
    costing_strategy: 'استراتيجية التكاليف والتسعير',
    costing_strategy_desc: 'حدد نسب تكاليفك عشان نفعّلك التسعير الذكي للأصناف الجديدة.',
    labor_cost_perc: 'نسبة تكلفة العمالة (%)',
    overhead_cost_perc: 'نسبة المصاريف الثابتة (%)',
    target_profit_margin: 'هامش الربح المستهدف (%)',
    target_food_cost_perc: 'نسبة تكلفة الأكل المستهدفة',
    target_food_cost_desc: 'النسبة الباقية من سعر البيع بعد ما تغطي كل التكاليف والربح المستهدف.',
    create_menu_item: 'اعمل صنف في المنيو',
    intelligent_pricing: 'التسعير الذكي للصنف',
    based_on_recipe: 'بناءً على وصفة:',
    recipe_food_cost: 'تكلفة أكل الوصفة',
    suggested_selling_price: 'سعر البيع المقترح',
    how_price_was_calculated: 'السعر ده اتحسب إزاي؟',
    price_calculation_explanation: 'بناءً على إعدادات التكاليف بتاعتك، السعر المقترح ده بيضمن تغطية كل مصاريفك وتحقيق الربح اللي انت عايزه.',
    formula: 'المعادلة',
    final_price: 'سعر البيع النهائي',
    menu_item_name: 'اسم الصنف في المنيو',
    add_to_menu: 'ضيف للمنيو',
    item_added_to_menu_success: 'الصنف نزل في المنيو بنجاح!',
    add_edit_recipe: 'إضافة/تعديل وصفة',
    edit_recipe: 'تعديل وصفة',
    add_ingredient: 'ضيف مكون',
    search_ingredient: 'دور على مكون من المخزن...',
    quantity: 'الكمية',
    unit: 'الوحدة',
    cost: 'التكلفة',
    total_food_cost: 'إجمالي تكلفة الأكل',
    save_recipe: 'احفظ الوصفة',
    delete_recipe: 'امسح الوصفة',
    recipe_saved_success: 'الوصفة اتحفظت بنجاح!',
    recipe_deleted_success: 'الوصفة اتمسحت!',
    is_sub_recipe: 'وصفة تحضيرية',
    wastage_perc: 'نسبة الهدر (%)',
    yield_perc: 'نسبة الإنتاجية (%)',
    effective_cost: 'التكلفة الفعلية',
    base_cost: 'التكلفة الأساسية',
    final_cost: 'التكلفة النهائية',
    search_inventory_or_subrecipe: 'دور على مكون أو وصفة تحضيرية...',
    mark_as_sub_recipe: 'اعتبرها "وصفة تحضيرية"',
    sub_recipe_explanation: 'الوصفات التحضيرية (زي الصوصات) ممكن تستخدمها كمكونات في وصفات تانية.',
    final_recipe_cost: 'التكلفة النهائية للوصفة',
    production_yield: 'إنتاجية التحضيرة',
    yield_unit: 'وحدة الإنتاج',
    instructions: 'طريقة التحضير',
    allergens: 'مسببات الحساسية',
    cost_per_portion: 'تكلفة البورشن',
    total_batch_cost: 'تكلفة التحضيرة كلها',
    no_allergens_detected: 'مفيش أي مسببات حساسية.',
    dairy: 'ألبان',
    gluten: 'جلوتين',
    nuts: 'مكسرات',
    portion: 'بورشن',
    kg: 'كيلو',
    g: 'جرام',
    L: 'لتر',
    ml: 'مل',
    unit_piece: 'قطعة',
    soy: 'صويا',
    fish: 'سمك',
    shellfish: 'قشريات',
    eggs: 'بيض',
    welcome_to: 'أهلاً بك في',
    invalid_credentials: 'الإيميل أو الباسورد غلط. حاول تاني.',
    login_as_manager: 'دخول كمدير',
    login_as_employee: 'دخول كموظف',
    login: 'دخول',
    employee_portal: 'بوابة الموظفين',
    my_profile: 'صفحتي الشخصية',
    my_attendance: 'حضوري وانصرافي',
    my_leave_requests: 'طلبات أجازاتي',
    personal_information: 'البيانات الشخصية هتظهر هنا.',
    request_leave: 'اطلب أجازة',
    request_date: 'تاريخ الطلب',
    no_leave_requests: 'معندكش طلبات أجازة.',
    annual: 'سنوي',
    sick: 'مرضي',
    unpaid: 'بدون مرتب',
    reason_placeholder: 'اكتب سبب الأجازة هنا...',
    submit_request: 'ابعت الطلب',
    cancel: 'إلغاء',
    overview: 'نظرة عامة',
    sales_hub: 'ملخص المبيعات',
    hr_hub: 'ملخص الموظفين',
    inventory_hub: 'ملخص المخزن',
    predictive_analysis: 'تحليل توقعي',
    predictive_analysis_prompt: 'دوس عشان تشوف توقعات المبيعات للشهر الجاي بناءً على البيانات الحالية.',
    generating_prediction: 'بنعمل التوقع...',
    predict: 'اعمل توقع',
    ask_ai_about_data: 'اسأل الذكاء الاصطناعي أي حاجة عن بياناتك...',
    ai_command_executing: 'الذكاء الاصطناعي بينفذ طلبك...',
    ai_command_unrecognized: 'معلش، مطلبك مش واضح. ممكن تحاول تاني؟',
    sales_summary: 'ملخص المبيعات',
    today: 'النهاردة',
    this_week: 'الأسبوع ده',
    branch_performance: 'أداء الفرع',
    orders: 'أوردرات',
    avg_order: 'متوسط الأوردر',
    live_order_feed: 'الأوردرات الحالية',
    top_selling_products: 'أكتر الأصناف مبيعًا',
    top_employees: 'أفضل الموظفين أداءً',
    total_revenue: 'إجمالي الإيراد',
    // FIX: Corrected translation for unpaid_invoices
    unpaid_invoices: 'فواتير غير مدفوعة',
    overdue_amount: 'مبالغ متأخرة',
    invoice_status_overview: 'حالة الفواتير',
    search_or_create_category: 'ابحث عن قسم أو أنشئ قسم جديد',
    recent_invoices: 'آخر الفواتير',
    total_employees: 'عدد الموظفين',
    turnover_rate: 'معدل دوران العمالة',
    pending_requests: 'طلبات معلقة',
    quick_links: 'روابط سريعة',
    view_all_employees: 'كل الموظفين',
    manage_leave: 'إدارة الأجازات',
    view_org_chart: 'الهيكل التنظيمي',
    new_hires: 'التعيينات الجديدة',
    upcoming_birthdays: 'أعياد ميلاد قريبة',
    low_stock_items: 'نواقص المخزن',
    notification_center: 'مركز الإشعارات',
    mark_all_as_read: 'قراءة الكل',
    no_new_notifications: 'مفيش إشعارات جديدة.',
    stock_alert: 'تنبيه مخزون',
    profile_and_settings: 'صفحتي والإعدادات',
    logout: 'خروج',
  },
  'en-US': {
    dashboard: 'Dashboard',
    pos: 'POS',
    sales: 'Sales',
    purchases: 'Purchases',
    inventory: 'Inventory',
    customers: 'Customers',
    hr: 'HR',
    attendance: 'Attendance',
    menu: 'Menu',
    recipes: 'Recipes & Costs',
    kitchen: 'Central Kitchen',
    delivery: 'Delivery Zones',
    branches: 'Branches',
    daily_ops: 'Daily Ops',
    pnl: 'Profit & Loss',
    reports: 'Reports',
    settings: 'Settings',
    system_name: 'Al-Nawaji Smart System',
    theme: 'Theme',
    language: 'Language',
    total_sales: 'Total Sales',
    new_customers: 'New Customers',
    avg_order_value: 'Avg. Order Value',
    top_selling_item: 'Top Selling Item',
    generating_kpis: 'Generating KPIs...',
    generate_menu_ideas: 'Generate Menu Ideas',
    generating_ideas: 'Generating Ideas...',
    order_total: 'Total',
    pay_now: 'Pay Now',
    categories: 'Categories',
    items: 'Items',
    your_order: 'Your Order',
    search_items: 'Search for items...',
    greeting: 'Welcome back,',
    subtitle: 'Here’s a quick summary of your activity today.',
    select_customer: 'Select Customer',
    walk_in_customer: 'Walk-in Customer',
    add_discount: 'Add Discount',
    cash: 'Cash',
    card: 'Card',
    online: 'Online',
    employee_management: 'Employee Management',
    employee_subtitle: 'View, search, and manage all employees in the system.',
    add_employee: 'Add Employee',
    search_employees: 'Search for employees...',
    generating_employees: 'Generating employee data...',
    name: 'Name',
    position: 'Position',
    branch: 'Branch',
    salary: 'Salary',
    status: 'Status',
    actions: 'Actions',
    view_details: 'View Details',
    view_short: 'View',
    edit_short: 'Edit',
    sales_management: 'Sales Management',
    sales_subtitle: 'Track all invoices and quotations from every branch.',
    add_sale: 'Add Invoice',
    search_sales: 'Search sales...',
    generating_sales: 'Generating sales data...',
    customer: 'Customer',
    total: 'Total',
    date: 'Date',
    inventory_management: 'Inventory Management',
    inventory_subtitle: 'Monitor stock levels, transfers, and reorder alerts.',
    add_item: 'Add Item',
    search_inventory: 'Search inventory...',
    generating_inventory: 'Generating inventory data...',
    item_name: 'Item Name',
    category: 'Category',
    stock_level: 'Stock Level',
    reorder_level: 'Reorder Level',
    supplier: 'Supplier',
    customer_management: 'Customer Management',
    customer_subtitle: 'Build and manage customer relationships and loyalty programs.',
    add_customer: 'Add Customer',
    search_customers: 'Search for customers...',
    generating_customers: 'Generating customer data...',
    email: 'Email',
    phone: 'Phone',
    loyalty_points: 'Loyalty Points',
    last_order: 'Last Order',
    purchases_management: 'Purchases Management',
    purchases_subtitle: 'Track purchase orders, invoices, and supplier relations.',
    add_purchase: 'Add Purchase',
    search_purchases: 'Search purchases...',
    generating_purchases: 'Generating purchase data...',
    order_id: 'Order ID',
    amount: 'Amount',
    attendance_management: 'Smart Attendance',
    attendance_subtitle: 'Monitor and analyze employee attendance with AI-powered insights.',
    search_attendance: 'Search attendance...',
    generating_attendance: 'Generating attendance records...',
    employee_name: 'Employee Name',
    check_in: 'Check-in',
    check_out: 'Check-out',
    duration: 'Duration',
    recipes_management: 'Recipes Management',
    recipes_subtitle: 'Create and manage recipes, track costs and profit margins.',
    add_recipe: 'Add Recipe',
    search_recipes: 'Search recipes...',
    generating_recipes: 'Generating recipe data...',
    recipe_name: 'Recipe Name',
    food_cost_perc: 'Food Cost %',
    gross_margin: 'Gross Margin',
    ingredients: 'Ingredients',
    kitchen_management: 'Central Kitchen Management',
    kitchen_subtitle: 'Coordinate preparation and distribution orders to branches.',
    search_kitchen_orders: 'Search kitchen orders...',
    generating_kitchen_orders: 'Generating kitchen orders...',
    destination_branch: 'Destination Branch',
    prep_status: 'Prep Status',
    prep_time: 'Prep Time',
    delivery_management: 'Delivery Zones Management',
    delivery_subtitle: 'Define delivery zones, fees, and track drivers.',
    add_zone: 'Add Zone',
    zone_name: 'Zone Name',
    delivery_fee: 'Delivery Fee',
    active_drivers: 'Active Drivers',
    avg_delivery_time: 'Avg. Delivery Time',
    branches_management: 'Branch Management',
    branches_subtitle: 'Oversee and manage the performance of all branches.',
    add_branch: 'Add Branch',
    branch_name: 'Branch Name',
    manager: 'Manager',
    employees: 'Employees',
    daily_sales: 'Daily Sales',
    daily_ops_management: 'Daily Operations Management',
    daily_ops_subtitle: 'Checklists and tasks to ensure smooth daily operations.',
    opening_checklist: 'Opening Checklist',
    closing_checklist: 'Closing Checklist',
    pnl_statement: 'Profit & Loss Statement',
    pnl_subtitle: 'Analyze financial performance for the current period.',
    revenue: 'Revenue',
    cogs: 'Cost of Goods Sold',
    gross_profit: 'Gross Profit',
    operating_expenses: 'Operating Expenses',
    net_profit: 'Net Profit',
    reports_center: 'Reports Center',
    reports_subtitle: 'Generate and export custom reports for the system.',
    report_name: 'Report Name',
    description: 'Description',
    last_generated: 'Last Generated',
    run_report: 'Run Report',
    settings_subtitle: 'Manage your system settings and preferences.',
    general_settings: 'General Settings',
    pos_settings: 'POS Settings',
    financial_settings: 'Financial Settings',
    users_roles: 'Users & Roles',
    inventory_settings: 'Inventory Settings',
    customer_loyalty: 'Customers & Loyalty',
    integrations: 'Integrations',
    security_data: 'Security & Data',
    company_profile: 'Company Profile',
    company_name: 'Company Name',
    company_logo: 'Company Logo',
    change_logo: 'Change Logo',
    company_address: 'Company Address',
    contact_email: 'Contact Email',
    localization: 'Localization',
    default_language: 'Default Language',
    default_currency: 'Default Currency',
    timezone: 'Timezone',
    date_format: 'Date Format',
    branch_settings: 'Branch Settings',
    allow_inter_branch_transfers: 'Allow Inter-Branch Transfers',
    default_branch_new_employees: 'Default Branch for New Employees',
    system_behavior: 'System Behavior',
    auto_logout_minutes: 'Auto-Logout (minutes)',
    enable_end_of_day_report_email: 'Enable End-of-Day Report Email',
    end_of_day_report_recipients: 'End-of-Day Report Recipients',
    payment_methods: 'Payment Methods',
    enable: 'Enable',
    receipt_customization: 'Receipt Customization',
    header_text: 'Header Text',
    footer_text: 'Footer Text',
    order_management: 'Order Management',
    enable_table_management: 'Enable Table Management',
    default_order_type: 'Default Order Type',
    dine_in: 'Dine-in',
    takeaway: 'Takeaway',
    delivery_option: 'Delivery',
    enable_order_hold: 'Enable Order Hold',
    print_kitchen_receipt_auto: 'Print Kitchen Receipt Automatically',
    gratuity_tipping: 'Gratuity & Tipping',
    enable_tipping_on_card_machine: 'Enable Tipping on Card Machine',
    suggested_tip_percentages: 'Suggested Tip Percentages',
    tax_settings: 'Tax Settings',
    vat_percentage: 'VAT Percentage',
    service_charge: 'Service Charge',
    tax_reg_number: 'Tax Registration Number',
    accounting: 'Accounting',
    fiscal_year_start: 'Fiscal Year Start',
    accounting_integration: 'Accounting Integration',
    auto_sync_daily_sales: 'Auto-Sync Daily Sales',
    expense_tracking: 'Expense Tracking',
    add_expense_category: 'Add Expense Category',
    user_management: 'User Management',
    invite_user: 'Invite User',
    role_based_access: 'Role-Based Access Control',
    add_role: 'Add Role',
    manager_role: 'Manager',
    cashier_role: 'Cashier',
    waiter_role: 'Waiter',
    advanced_permissions: 'Advanced Permissions',
    can_give_discounts_above: 'Can give discounts above',
    pnl_dashboard: 'Financial Dashboard',
    financial_kpis: 'Key Performance Indicators',
    gross_profit_margin: 'Gross Profit Margin',
    net_profit_margin: 'Net Profit Margin',
    ai_financial_summary: 'AI Financial Summary',
    generating_insights: 'Analyzing data...',
    date_range: 'Date Range',
    this_month: 'This Month',
    last_month: 'Last Month',
    this_quarter: 'This Quarter',
    this_year: 'This Year',
    all_branches: 'All Branches',
    view_mode: 'View Mode',
    standard: 'Standard',
    comparison_pop: 'Period-over-Period',
    percentage_of_revenue: '% of Revenue',
    budget_vs_actual: 'Budget vs. Actual',
    account: 'Account',
    current_period: 'Current Period',
    previous_period: 'Previous Period',
    variance: 'Variance',
    budget: 'Budget',
    actual: 'Actual',
    what_if_analysis: 'What-If Analysis',
    what_if_analysis_desc: 'Test the impact of hypothetical changes on your bottom line.',
    what_if_prompt: 'Enter a scenario, e.g., "What if rent increases by 10%?"',
    simulate: 'Simulate',
    base_case: 'Base Case',
    simulated_case: 'Simulated Case',
    tools: 'Financial Tools',
    manage_chart_of_accounts: 'Manage Chart of Accounts',
    manage_budgets: 'Manage Budgets',
    manual_journal_entry: 'Manual Journal Entry',
    close_period: 'Close Financial Period',
    export_pdf: 'Export PDF',
    export_excel: 'Export Excel',
    feature_in_development: 'This feature is in development',
    pos_source: 'POS',
    inventory_source: 'Inventory',
    hr_source: 'HR',
    manual_source: 'Manual',
    search_for_customers: 'Search customers by name or phone...',
    customer_profile: 'Customer Profile',
    select: 'Select',
    subtotal: 'Subtotal',
    tax: 'Tax (14%)',
    table_management: 'Table Management',
    active_orders: 'Active Orders',
    payment: 'Payment',
    payment_details: 'Payment Details',
    amount_received: 'Amount Received',
    change_due: 'Change Due',
    confirm_payment: 'Confirm Payment',
    order_paid_success: 'Order paid successfully!',
    new_order_for_table: 'New order started for table',
    no_active_order: 'No active order. Please select a table.',
    available: 'Available',
    occupied: 'Occupied',
    order_notes_placeholder: 'Order notes...',
    offline_mode_active: 'Offline mode active. Orders will sync when reconnected.',
    grid_view: 'Grid View',
    floor_plan: 'Floor Plan',
    split_bill: 'Split Bill',
    merge_tables: 'Merge Tables',
    gift_card: 'Gift Card',
    split_payment: 'Split Payment',
    print_receipt: 'Print Receipt',
    email_receipt: 'Email Receipt',
    split_by_item: 'Split by Item',
    split_equally: 'Split Equally',
    costing_strategy: 'Costing & Pricing Strategy',
    costing_strategy_desc: 'Define your cost percentages to enable smart pricing for new items.',
    labor_cost_perc: 'Labor Cost (%)',
    overhead_cost_perc: 'Overhead Cost (%)',
    target_profit_margin: 'Target Profit Margin (%)',
    target_food_cost_perc: 'Target Food Cost %',
    target_food_cost_desc: 'The remaining percentage of the selling price after all costs and target profit are covered.',
    create_menu_item: 'Create Menu Item',
    intelligent_pricing: 'Intelligent Item Pricing',
    based_on_recipe: 'Based on Recipe:',
    recipe_food_cost: 'Recipe Food Cost',
    suggested_selling_price: 'Suggested Selling Price',
    how_price_was_calculated: 'How was this price calculated?',
    price_calculation_explanation: 'Based on your costing settings, the suggested price is calculated to ensure all expenses are covered while achieving your target profit.',
    formula: 'Formula',
    final_price: 'Final Selling Price',
    menu_item_name: 'Menu Item Name',
    add_to_menu: 'Add to Menu',
    item_added_to_menu_success: 'Item added to menu successfully!',
    add_edit_recipe: 'Add/Edit Recipe',
    edit_recipe: 'Edit Recipe',
    add_ingredient: 'Add Ingredient',
    search_ingredient: 'Search for ingredient from inventory...',
    quantity: 'Quantity',
    unit: 'Unit',
    cost: 'Cost',
    total_food_cost: 'Total Food Cost',
    save_recipe: 'Save Recipe',
    delete_recipe: 'Delete Recipe',
    recipe_saved_success: 'Recipe saved successfully!',
    recipe_deleted_success: 'Recipe deleted successfully!',
    is_sub_recipe: 'Sub-recipe',
    wastage_perc: 'Wastage (%)',
    yield_perc: 'Yield (%)',
    effective_cost: 'Effective Cost',
    base_cost: 'Base Cost',
    final_cost: 'Final Cost',
    search_inventory_or_subrecipe: 'Search for an ingredient or sub-recipe...',
    mark_as_sub_recipe: 'Mark as "Sub-recipe"',
    sub_recipe_explanation: 'Sub-recipes can be used as ingredients in other recipes.',
    final_recipe_cost: 'Final Recipe Cost',
    production_yield: 'Production Yield',
    yield_unit: 'Yield Unit',
    instructions: 'Instructions',
    allergens: 'Allergens',
    cost_per_portion: 'Cost Per Portion',
    total_batch_cost: 'Total Batch Cost',
    no_allergens_detected: 'No allergens detected.',
    dairy: 'Dairy',
    gluten: 'Gluten',
    nuts: 'Nuts',
    portion: 'Portion',
    kg: 'kg',
    g: 'g',
    L: 'L',
    ml: 'ml',
    unit_piece: 'Piece',
    soy: 'Soy',
    fish: 'Fish',
    shellfish: 'Shellfish',
    eggs: 'Eggs',
    welcome_to: 'Welcome to',
    invalid_credentials: 'Invalid email or password. Please try again.',
    login_as_manager: 'Login as Manager',
    login_as_employee: 'Login as Employee',
    login: 'Login',
    employee_portal: 'Employee Portal',
    my_profile: 'My Profile',
    my_attendance: 'My Attendance',
    my_leave_requests: 'My Leave Requests',
    personal_information: 'Personal information will be displayed here.',
    request_leave: 'Request Leave',
    request_date: 'Request Date',
    no_leave_requests: 'You have no leave requests.',
    annual: 'Annual',
    sick: 'Sick',
    unpaid: 'Unpaid',
    reason_placeholder: 'Enter reason for leave here...',
    submit_request: 'Submit Request',
    cancel: 'Cancel',
    overview: 'Overview',
    sales_hub: 'Sales Hub',
    hr_hub: 'HR Hub',
    inventory_hub: 'Inventory Hub',
    predictive_analysis: 'Predictive Analysis',
    predictive_analysis_prompt: 'Click to see next month\'s sales forecast based on current data.',
    generating_prediction: 'Generating...',
    predict: 'Predict',
    ask_ai_about_data: 'Ask AI anything about your data...',
    ai_command_executing: 'AI is processing your command...',
    ai_command_unrecognized: 'Sorry, I didn\'t understand that. Could you try again?',
    sales_summary: 'Sales Summary',
    today: 'Today',
    this_week: 'This Week',
    branch_performance: 'Branch Performance',
    orders: 'Orders',
    avg_order: 'Avg. Order',
    live_order_feed: 'Live Order Feed',
    top_selling_products: 'Top Selling Products',
    top_employees: 'Top Employees',
    total_revenue: 'Total Revenue',
    unpaid_invoices: 'Unpaid Invoices',
    overdue_amount: 'Overdue Amount',
    invoice_status_overview: 'Invoice Status Overview',
    search_or_create_category: 'Search or create a category',
    recent_invoices: 'Recent Invoices',
    total_employees: 'Total Employees',
    turnover_rate: 'Turnover Rate',
    pending_requests: 'Pending Requests',
    quick_links: 'Quick Links',
    view_all_employees: 'View All Employees',
    manage_leave: 'Manage Leave',
    view_org_chart: 'View Org Chart',
    new_hires: 'New Hires',
    upcoming_birthdays: 'Upcoming Birthdays',
    low_stock_items: 'Low Stock Items',
    notification_center: 'Notification Center',
    mark_all_as_read: 'Mark all as read',
    no_new_notifications: 'No new notifications.',
    stock_alert: 'Stock Alert',
    profile_and_settings: 'Profile & Settings',
    logout: 'Logout',
  }
};

interface LocalizationContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: keyof typeof translations['en-US'], fallback?: string) => string;
  isRtl: boolean;
}

export const LocalizationContext = createContext<LocalizationContextType | undefined>(undefined);

export const LocalizationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<Locale>(() => {
    const savedLocale = localStorage.getItem('app-locale') as Locale;
    return savedLocale || 'ar-EG';
  });

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('app-locale', newLocale);
  };

  useEffect(() => {
    document.documentElement.lang = locale.split('-')[0];
    document.documentElement.dir = locale === 'ar-EG' ? 'rtl' : 'ltr';
  }, [locale]);

  const t = useCallback((key: keyof typeof translations['en-US'], fallback?: string): string => {
    return translations[locale]?.[key] || fallback || key;
  }, [locale]);

  return (
    <LocalizationContext.Provider value={{ locale, setLocale, t, isRtl: locale === 'ar-EG' }}>
      {children}
    </LocalizationContext.Provider>
  );
};